project:
  type: manuscript

manuscript:
  article: artigo.qmd

format:
  html:
    theme:
      light: cosmo
      dark: vapor
  docx: default
  pdf:
    documentclass: scrreprt
    include-in-header:  
      - text: |
          \usepackage{musicography}
editor:
  render-on-save: true
execute:
  freeze: auto
