project:
  type: manuscript

manuscript:
  article: artigo.qmd

format:
  html:
    comments:
      hypothesis: true
  docx: default
  pdf:
    documentclass: scrreprt

editor:
  render-on-save: true
execute:
  freeze: auto



